export const countries = {
    en: [
        "Australia",
        "Austria",
        "Azerbaijan",
        "Albania",
        "Algeria",
        "Angola",
        "Andorra",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Afghanistan",
        "Bahamas",
        "Bangladesh",
        "Barbados",
        "Bahrain",
        "Belarus",
        "Belize",
        "Belgium",
        "Benin",
        "Bulgaria",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Burkina Faso",
        "Burundi",
        "Bhutan",
        "Vanuatu",
        "Vatican City",
        "United Kingdom",
        "Hungary",
        "Venezuela",
        "East Timor",
        "Vietnam",
        "Gabon",
        "Haiti",
        "Guyana",
        "Gambia",
        "Ghana",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Germany",
        "Honduras",
        "Grenada",
        "Greece",
        "Georgia",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Egypt",
        "Zambia",
        "Zimbabwe",
        "Israel",
        "India",
        "Indonesia",
        "Jordan",
        "Iraq",
        "Iran",
        "Ireland",
        "Iceland",
        "Spain",
        "Italy",
        "Yemen",
        "Cape Verde",
        "Kazakhstan",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Qatar",
        "Kenya",
        "Cyprus",
        "Kyrgyzstan",
        "Kiribati",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Ivory Coast",
        "Cuba",
        "Kuwait",
        "Laos",
        "Latvia",
        "Lesotho",
        "Liberia",
        "Lebanon",
        "Libya",
        "Lithuania",
        "Liechtenstein",
        "Luxembourg",
        "Mauritius",
        "Mauritania",
        "Madagascar",
        "Macedonia",
        "Malawi",
        "Malaysia",
        "Mali",
        "Maldives",
        "Malta",
        "Morocco",
        "Marshall Islands",
        "Mexico",
        "Micronesia",
        "Mozambique",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Niger",
        "Nigeria",
        "Netherlands",
        "Nicaragua",
        "New Zealand",
        "Norway",
        "UAE",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Poland",
        "Portugal",
        "Russia",
        "Rwanda",
        "Romania",
        "El Salvador",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "North Korea",
        "Seychelles",
        "Senegal",
        "Saint Vincent and the Grenadines",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Serbia",
        "Singapore",
        "Syria",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "Sudan",
        "Suriname",
        "USA",
        "Sierra Leone",
        "Tajikistan",
        "Thailand",
        "Tanzania",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tuvalu",
        "Tunisia",
        "Turkmenistan",
        "Turkey",
        "Uganda",
        "Uzbekistan",
        "Ukraine",
        "Uruguay",
        "Fiji",
        "Philippines",
        "Finland",
        "France",
        "Croatia",
        "Central African Republic",
        "Chad",
        "Montenegro",
        "Czech Republic",
        "Chile",
        "Switzerland",
        "Sweden",
        "Sri Lanka",
        "Ecuador",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Estonia",
        "Ethiopia",
        "South Korea",
        "South Sudan",
        "South Africa",
        "Jamaica",
        "Japan"
    ],
    ru: [
        "Австралия",
        "Австрия",
        "Азербайджан",
        "Албания",
        "Алжир",
        "Ангола",
        "Андорра",
        "Антигуа и Барбуда",
        "Аргентина",
        "Армения",
        "Афганистан",
        "Багамские Острова",
        "Бангладеш",
        "Барбадос",
        "Бахрейн",
        "Беларусь",
        "Белиз",
        "Бельгия",
        "Бенин",
        "Болгария",
        "Боливия",
        "Босния и Герцеговина",
        "Ботсвана",
        "Бразилия",
        "Бруней",
        "Буркина-Фасо",
        "Бурунди",
        "Бутан",
        "Вануату",
        "Ватикан",
        "Великобритания",
        "Венгрия",
        "Венесуэла",
        "Восточный Тимор",
        "Вьетнам",
        "Габон",
        "Гаити",
        "Гайана",
        "Гамбия",
        "Гана",
        "Гватемала",
        "Гвинея",
        "Гвинея-Бисау",
        "Германия",
        "Гондурас",
        "Гренада",
        "Греция",
        "Грузия",
        "Дания",
        "Джибути",
        "Доминика",
        "Доминиканская Республика",
        "Египет",
        "Замбия",
        "Зимбабве",
        "Израиль",
        "Индия",
        "Индонезия",
        "Иордания",
        "Ирак",
        "Иран",
        "Ирландия",
        "Исландия",
        "Испания",
        "Италия",
        "Йемен",
        "Кабо-Верде",
        "Казахстан",
        "Камбоджа",
        "Камерун",
        "Канада",
        "Катар",
        "Кения",
        "Кипр",
        "Киргизия",
        "Кирибати",
        "Китай",
        "Колумбия",
        "Коморы",
        "Конго",
        "Коста-Рика",
        "Кот-д'Ивуар",
        "Куба",
        "Кувейт",
        "Лаос",
        "Латвия",
        "Лесото",
        "Либерия",
        "Ливан",
        "Ливия",
        "Литва",
        "Лихтенштейн",
        "Люксембург",
        "Маврикий",
        "Мавритания",
        "Мадагаскар",
        "Македония",
        "Малави",
        "Малайзия",
        "Мали",
        "Мальдивы",
        "Мальта",
        "Марокко",
        "Маршалловы Острова",
        "Мексика",
        "Микронезия",
        "Мозамбик",
        "Молдова",
        "Монако",
        "Монголия",
        "Мьянма",
        "Намибия",
        "Науру",
        "Непал",
        "Нигер",
        "Нигерия",
        "Нидерланды",
        "Никарагуа",
        "Новая Зеландия",
        "Норвегия",
        "ОАЭ",
        "Оман",
        "Пакистан",
        "Палау",
        "Панама",
        "Папуа-Новая Гвинея",
        "Парагвай",
        "Перу",
        "Польша",
        "Португалия",
        "Россия",
        "Руанда",
        "Румыния",
        "Сальвадор",
        "Самоа",
        "Сан-Марино",
        "Сан-Томе и Принсипи",
        "Саудовская Аравия",
        "Северная Корея",
        "Сейшельские Острова",
        "Сенегал",
        "Сент-Винсент и Гренадины",
        "Сент-Китс и Невис",
        "Сент-Люсия",
        "Сербия",
        "Сингапур",
        "Сирия",
        "Словакия",
        "Словения",
        "Соломоновы Острова",
        "Сомали",
        "Судан",
        "Суринам",
        "США",
        "Сьерра-Леоне",
        "Таджикистан",
        "Таиланд",
        "Танзания",
        "Того",
        "Тонга",
        "Тринидад и Тобаго",
        "Тувалу",
        "Тунис",
        "Туркменистан",
        "Турция",
        "Уганда",
        "Узбекистан",
        "Украина",
        "Уругвай",
        "Фиджи",
        "Филиппины",
        "Финляндия",
        "Франция",
        "Хорватия",
        "Центральноафриканская Республика",
        "Чад",
        "Черногория",
        "Чехия",
        "Чили",
        "Швейцария",
        "Швеция",
        "Шри-Ланка",
        "Эквадор",
        "Экваториальная Гвинея",
        "Эритрея",
        "Эсватини",
        "Эстония",
        "Эфиопия",
        "Южная Корея",
        "Южный Судан",
        "Южно-Африканская Республика",
        "Ямайка",
        "Япония"
    ]
}