import {ref} from "vue";

export const iconsLanguage = ref({
    js: "logos:javascript",
    javascript: "logos:javascript",
    ts: "logos:typescript-icon",
    typescript: "logos:typescript-icon",
    vue: "logos:vue",
    react: "logos:react",
    angular: "logos:angular-icon",
    svelte: "logos:svelte-icon",
    astro: "logos:astro-icon",
    html:"logos:html-5",
    tailwind: "logos:tailwindcss-icon",
    css: "logos:css-3",
    less: "logos:less",
    postcss: "logos:postcss",
    sass: "logos:sass",
    json: "logos:json",
    npm:"logos:npm-icon",
    yarn:"logos:yarn",
    pnpm:"logos:pnpm",
    nuxt: "logos:nuxt-icon",
    nodejs: "logos:nodejs-icon",
    docker: "logos:docker-icon",
    dockerfile: "logos:docker-icon",
    Dockerfile: "logos:docker-icon",
    vite: "logos:vitejs",
    rollup: "logos:rollupjs",
    eslint: "logos:eslint",
    jest: "logos:jest",
    vitest: "logos:vitest",
    azure: "logos:azure",
    md: "logos:markdown",
    markdown: "logos:markdown",
})